development:
  adapter: async
  channel_prefix: codepeer_review_development

test:
  adapter: test

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: codepeer_review_production
  
