development:
  adapter: postgresql
  database: codepeer_review_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: codepeer_review_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: codepeer_review_production
  pool: 5
  timeout: 5000

